# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T11:16:23+00:00



import argparse
import json
import os
from typing import *
from typing import Optional, Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity, HTTPBasic
from fastapi import Path, Query
from pydantic import conint, constr
from starlette.requests import Request

from models import (
    TrunkingV1Trunk,
    TrunkingV1TrunkCredentialList,
    TrunkingV1TrunkIpAccessControlList,
    TrunkingV1TrunkOriginationUrl,
    TrunkingV1TrunkPhoneNumber,
    TrunkingV1TrunkRecording,
    V1TrunksGetResponse,
    V1TrunksTrunkSidCredentialListsGetResponse,
    V1TrunksTrunkSidIpAccessControlListsGetResponse,
    V1TrunksTrunkSidOriginationUrlsGetResponse,
    V1TrunksTrunkSidPhoneNumbersGetResponse,
)

app = MCPProxy(
    contact={
        'email': 'support@twilio.com',
        'name': 'Twilio Support',
        'url': 'https://support.twilio.com',
    },
    description='This is the public Twilio REST API.',
    license={
        'name': 'Apache 2.0',
        'url': 'https://www.apache.org/licenses/LICENSE-2.0.html',
    },
    termsOfService='https://www.twilio.com/legal/tos',
    title='Twilio - Trunking',
    version='1.42.0',
    servers=[{'url': 'https://trunking.twilio.com'}],
)


@app.get(
    '/v1/Trunks',
    tags=['trunk_operations'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def list_trunk(
    page_size: Optional[conint(ge=1, le=1000)] = Query(None, alias='PageSize'),
    page: Optional[conint(ge=0)] = Query(None, alias='Page'),
    page_token: Optional[str] = Query(None, alias='PageToken'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Trunks',
    tags=['trunk_operations'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def create_trunk(request: Request):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/v1/Trunks/{Sid}',
    tags=['credential_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def delete_trunk(
    sid: constr(pattern=r'^TK[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    )
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Trunks/{Sid}',
    tags=['credential_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_trunk(
    sid: constr(pattern=r'^TK[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    )
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Trunks/{Sid}',
    tags=[
        'trunk_operations',
        'credential_management',
        'ip_access_control_management',
        'origination_url_operations',
        'phone_number_operations',
        'recording_operations',
    ],
    security=[
        HTTPBasic(name="None"),
    ],
)
def update_trunk(
    sid: constr(pattern=r'^TK[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    ),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Trunks/{TrunkSid}/CredentialLists',
    tags=['trunk_operations'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def list_credential_list(
    trunk_sid: constr(
        pattern=r'^TK[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='TrunkSid'),
    page_size: Optional[conint(ge=1, le=1000)] = Query(None, alias='PageSize'),
    page: Optional[conint(ge=0)] = Query(None, alias='Page'),
    page_token: Optional[str] = Query(None, alias='PageToken'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Trunks/{TrunkSid}/CredentialLists',
    tags=['trunk_operations'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def create_credential_list(
    trunk_sid: constr(
        pattern=r'^TK[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='TrunkSid'),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/v1/Trunks/{TrunkSid}/CredentialLists/{Sid}',
    tags=['trunk_operations'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def delete_credential_list(
    trunk_sid: constr(
        pattern=r'^TK[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='TrunkSid'),
    sid: constr(pattern=r'^CL[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    ),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Trunks/{TrunkSid}/CredentialLists/{Sid}',
    tags=['trunk_operations'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_credential_list(
    trunk_sid: constr(
        pattern=r'^TK[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='TrunkSid'),
    sid: constr(pattern=r'^CL[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    ),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Trunks/{TrunkSid}/IpAccessControlLists',
    description=""" List all IP Access Control Lists for a Trunk """,
    tags=['trunk_operations'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def list_ip_access_control_list(
    trunk_sid: constr(
        pattern=r'^TK[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='TrunkSid'),
    page_size: Optional[conint(ge=1, le=1000)] = Query(None, alias='PageSize'),
    page: Optional[conint(ge=0)] = Query(None, alias='Page'),
    page_token: Optional[str] = Query(None, alias='PageToken'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Trunks/{TrunkSid}/IpAccessControlLists',
    description=""" Associate an IP Access Control List with a Trunk """,
    tags=['trunk_operations', 'ip_access_control_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def create_ip_access_control_list(
    trunk_sid: constr(
        pattern=r'^TK[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='TrunkSid'),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/v1/Trunks/{TrunkSid}/IpAccessControlLists/{Sid}',
    description=""" Remove an associated IP Access Control List from a Trunk """,
    tags=['trunk_operations', 'credential_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def delete_ip_access_control_list(
    trunk_sid: constr(
        pattern=r'^TK[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='TrunkSid'),
    sid: constr(pattern=r'^AL[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    ),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Trunks/{TrunkSid}/IpAccessControlLists/{Sid}',
    tags=['trunk_operations'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_ip_access_control_list(
    trunk_sid: constr(
        pattern=r'^TK[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='TrunkSid'),
    sid: constr(pattern=r'^AL[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    ),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Trunks/{TrunkSid}/OriginationUrls',
    tags=['trunk_operations'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def list_origination_url(
    trunk_sid: constr(
        pattern=r'^TK[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='TrunkSid'),
    page_size: Optional[conint(ge=1, le=1000)] = Query(None, alias='PageSize'),
    page: Optional[conint(ge=0)] = Query(None, alias='Page'),
    page_token: Optional[str] = Query(None, alias='PageToken'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Trunks/{TrunkSid}/OriginationUrls',
    tags=['trunk_operations'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def create_origination_url(
    trunk_sid: constr(
        pattern=r'^TK[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='TrunkSid'),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/v1/Trunks/{TrunkSid}/OriginationUrls/{Sid}',
    tags=['trunk_operations', 'credential_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def delete_origination_url(
    trunk_sid: constr(
        pattern=r'^TK[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='TrunkSid'),
    sid: constr(pattern=r'^OU[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    ),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Trunks/{TrunkSid}/OriginationUrls/{Sid}',
    tags=['trunk_operations'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_origination_url(
    trunk_sid: constr(
        pattern=r'^TK[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='TrunkSid'),
    sid: constr(pattern=r'^OU[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    ),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Trunks/{TrunkSid}/OriginationUrls/{Sid}',
    tags=['trunk_operations'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def update_origination_url(
    trunk_sid: constr(
        pattern=r'^TK[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='TrunkSid'),
    sid: constr(pattern=r'^OU[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    ),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Trunks/{TrunkSid}/PhoneNumbers',
    tags=['trunk_operations'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def list_phone_number(
    trunk_sid: constr(
        pattern=r'^TK[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='TrunkSid'),
    page_size: Optional[conint(ge=1, le=1000)] = Query(None, alias='PageSize'),
    page: Optional[conint(ge=0)] = Query(None, alias='Page'),
    page_token: Optional[str] = Query(None, alias='PageToken'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Trunks/{TrunkSid}/PhoneNumbers',
    tags=['trunk_operations'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def create_phone_number(
    trunk_sid: constr(
        pattern=r'^TK[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='TrunkSid'),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/v1/Trunks/{TrunkSid}/PhoneNumbers/{Sid}',
    tags=['trunk_operations', 'credential_management', 'phone_number_operations'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def delete_phone_number(
    trunk_sid: constr(
        pattern=r'^TK[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='TrunkSid'),
    sid: constr(pattern=r'^PN[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    ),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Trunks/{TrunkSid}/PhoneNumbers/{Sid}',
    tags=[
        'trunk_operations',
        'credential_management',
        'ip_access_control_management',
        'origination_url_operations',
        'phone_number_operations',
        'recording_operations',
    ],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_phone_number(
    trunk_sid: constr(
        pattern=r'^TK[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='TrunkSid'),
    sid: constr(pattern=r'^PN[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    ),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Trunks/{TrunkSid}/Recording',
    tags=['trunk_operations'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_recording(
    trunk_sid: constr(
        pattern=r'^TK[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='TrunkSid')
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Trunks/{TrunkSid}/Recording',
    tags=['trunk_operations'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def update_recording(
    trunk_sid: constr(
        pattern=r'^TK[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='TrunkSid'),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
