# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T11:16:23+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import AnyUrl, BaseModel, Field, constr


class PhoneNumberEnumAddressRequirement(Enum):
    none = 'none'
    any = 'any'
    local = 'local'
    foreign = 'foreign'


class RecordingEnumRecordingMode(Enum):
    do_not_record = 'do-not-record'
    record_from_ringing = 'record-from-ringing'
    record_from_answer = 'record-from-answer'
    record_from_ringing_dual = 'record-from-ringing-dual'
    record_from_answer_dual = 'record-from-answer-dual'


class RecordingEnumRecordingTrim(Enum):
    trim_silence = 'trim-silence'
    do_not_trim = 'do-not-trim'


class TrunkEnumTransferCallerId(Enum):
    from_transferee = 'from-transferee'
    from_transferor = 'from-transferor'


class TrunkEnumTransferSetting(Enum):
    disable_all = 'disable-all'
    enable_all = 'enable-all'
    sip_only = 'sip-only'


class DisasterRecoveryMethod(Enum):
    HEAD = 'HEAD'
    GET = 'GET'
    POST = 'POST'
    PATCH = 'PATCH'
    PUT = 'PUT'
    DELETE = 'DELETE'


class TrunkingV1Trunk(BaseModel):
    account_sid: Optional[
        constr(pattern=r'^AC[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Trunk resource.',
    )
    auth_type: Optional[str] = Field(
        None,
        description='The types of authentication mapped to the domain. Can be: `IP_ACL` and `CREDENTIAL_LIST`. If both are mapped, the values are returned in a comma delimited list. If empty, the domain will not receive any traffic.',
    )
    auth_type_set: Optional[List[str]] = Field(None, description='Reserved.')
    cnam_lookup_enabled: Optional[bool] = Field(
        None,
        description='Whether Caller ID Name (CNAM) lookup is enabled for the trunk. If enabled, all inbound calls to the SIP Trunk from the United States and Canada automatically perform a CNAM Lookup and display Caller ID data on your phone. See [CNAM Lookups](https://www.twilio.com/docs/sip-trunking#CNAM) for more information.',
    )
    date_created: Optional[datetime] = Field(
        None,
        description='The date and time in GMT when the resource was created specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.',
    )
    date_updated: Optional[datetime] = Field(
        None,
        description='The date and time in GMT when the resource was last updated specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.',
    )
    disaster_recovery_method: Optional[DisasterRecoveryMethod] = Field(
        None,
        description='The HTTP method we use to call the `disaster_recovery_url`. Can be: `GET` or `POST`.',
    )
    disaster_recovery_url: Optional[AnyUrl] = Field(
        None,
        description='The URL we call using the `disaster_recovery_method` if an error occurs while sending SIP traffic towards the configured Origination URL. We retrieve TwiML from this URL and execute the instructions like any other normal TwiML call. See [Disaster Recovery](https://www.twilio.com/docs/sip-trunking#disaster-recovery) for more information.',
    )
    domain_name: Optional[str] = Field(
        None,
        description='The unique address you reserve on Twilio to which you route your SIP traffic. Domain names can contain letters, digits, and `-` and must end with `pstn.twilio.com`. See [Termination Settings](https://www.twilio.com/docs/sip-trunking#termination) for more information.',
    )
    friendly_name: Optional[str] = Field(
        None, description='The string that you assigned to describe the resource.'
    )
    links: Optional[Dict[str, Any]] = Field(
        None, description='The URLs of related resources.'
    )
    recording: Optional[Any] = Field(
        None,
        description="The recording settings for the trunk. Can be: `do-not-record`, `record-from-ringing`, `record-from-answer`. If set to `record-from-ringing` or `record-from-answer`, all calls going through the trunk will be recorded. The only way to change recording parameters is on a sub-resource of a Trunk after it has been created. e.g.`/Trunks/[Trunk_SID]/Recording -XPOST -d'Mode=record-from-answer'`. See [Recording](https://www.twilio.com/docs/sip-trunking#recording) for more information.",
    )
    secure: Optional[bool] = Field(
        None,
        description='Whether Secure Trunking is enabled for the trunk. If enabled, all calls going through the trunk will be secure using SRTP for media and TLS for signaling. If disabled, then RTP will be used for media. See [Secure Trunking](https://www.twilio.com/docs/sip-trunking#securetrunking) for more information.',
    )
    sid: Optional[
        constr(pattern=r'^TK[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The unique string that we created to identify the Trunk resource.',
    )
    transfer_caller_id: Optional[TrunkEnumTransferCallerId] = Field(
        None,
        description='Caller Id for transfer target. Can be: `from-transferee` (default) or `from-transferor`.',
    )
    transfer_mode: Optional[TrunkEnumTransferSetting] = Field(
        None,
        description='The call transfer settings for the trunk. Can be: `enable-all`, `sip-only` and `disable-all`. See [Transfer](https://www.twilio.com/docs/sip-trunking/call-transfer) for more information.',
    )
    url: Optional[AnyUrl] = Field(None, description='The absolute URL of the resource.')


class TrunkingV1TrunkCredentialList(BaseModel):
    account_sid: Optional[
        constr(pattern=r'^AC[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the CredentialList resource.',
    )
    date_created: Optional[datetime] = Field(
        None,
        description='The date and time in GMT when the resource was created specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.',
    )
    date_updated: Optional[datetime] = Field(
        None,
        description='The date and time in GMT when the resource was last updated specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.',
    )
    friendly_name: Optional[str] = Field(
        None, description='The string that you assigned to describe the resource.'
    )
    sid: Optional[
        constr(pattern=r'^CL[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The unique string that we created to identify the CredentialList resource.',
    )
    trunk_sid: Optional[
        constr(pattern=r'^TK[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None, description='The SID of the Trunk the credential list in associated with.'
    )
    url: Optional[AnyUrl] = Field(None, description='The absolute URL of the resource.')


class TrunkingV1TrunkIpAccessControlList(BaseModel):
    account_sid: Optional[
        constr(pattern=r'^AC[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the IpAccessControlList resource.',
    )
    date_created: Optional[datetime] = Field(
        None,
        description='The date and time in GMT when the resource was created specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.',
    )
    date_updated: Optional[datetime] = Field(
        None,
        description='The date and time in GMT when the resource was last updated specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.',
    )
    friendly_name: Optional[str] = Field(
        None, description='The string that you assigned to describe the resource.'
    )
    sid: Optional[
        constr(pattern=r'^AL[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The unique string that we created to identify the IpAccessControlList resource.',
    )
    trunk_sid: Optional[
        constr(pattern=r'^TK[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(None, description='The SID of the Trunk the resource is associated with.')
    url: Optional[AnyUrl] = Field(None, description='The absolute URL of the resource.')


class TrunkingV1TrunkOriginationUrl(BaseModel):
    account_sid: Optional[
        constr(pattern=r'^AC[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the OriginationUrl resource.',
    )
    date_created: Optional[datetime] = Field(
        None,
        description='The date and time in GMT when the resource was created specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.',
    )
    date_updated: Optional[datetime] = Field(
        None,
        description='The date and time in GMT when the resource was last updated specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.',
    )
    enabled: Optional[bool] = Field(
        None, description='Whether the URL is enabled. The default is `true`.'
    )
    friendly_name: Optional[str] = Field(
        None, description='The string that you assigned to describe the resource.'
    )
    priority: Optional[int] = Field(
        None,
        description='The relative importance of the URI. Can be an integer from 0 to 65535, inclusive, and the default is 10. The lowest number represents the most important URI.',
    )
    sid: Optional[
        constr(pattern=r'^OU[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The unique string that we created to identify the OriginationUrl resource.',
    )
    sip_url: Optional[AnyUrl] = Field(
        None,
        description='The SIP address you want Twilio to route your Origination calls to. This must be a `sip:` schema.',
    )
    trunk_sid: Optional[
        constr(pattern=r'^TK[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(None, description='The SID of the Trunk that owns the Origination URL.')
    url: Optional[AnyUrl] = Field(None, description='The absolute URL of the resource.')
    weight: Optional[int] = Field(
        None,
        description='The value that determines the relative share of the load the URI should receive compared to other URIs with the same priority. Can be an integer from 1 to 65535, inclusive, and the default is 10. URLs with higher values receive more load than those with lower ones with the same priority.',
    )


class SmsFallbackMethod(Enum):
    HEAD = 'HEAD'
    GET = 'GET'
    POST = 'POST'
    PATCH = 'PATCH'
    PUT = 'PUT'
    DELETE = 'DELETE'


class SmsMethod(Enum):
    HEAD = 'HEAD'
    GET = 'GET'
    POST = 'POST'
    PATCH = 'PATCH'
    PUT = 'PUT'
    DELETE = 'DELETE'


class StatusCallbackMethod(Enum):
    HEAD = 'HEAD'
    GET = 'GET'
    POST = 'POST'
    PATCH = 'PATCH'
    PUT = 'PUT'
    DELETE = 'DELETE'


class VoiceFallbackMethod(Enum):
    HEAD = 'HEAD'
    GET = 'GET'
    POST = 'POST'
    PATCH = 'PATCH'
    PUT = 'PUT'
    DELETE = 'DELETE'


class VoiceMethod(Enum):
    HEAD = 'HEAD'
    GET = 'GET'
    POST = 'POST'
    PATCH = 'PATCH'
    PUT = 'PUT'
    DELETE = 'DELETE'


class TrunkingV1TrunkPhoneNumber(BaseModel):
    account_sid: Optional[
        constr(pattern=r'^AC[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the PhoneNumber resource.',
    )
    address_requirements: Optional[PhoneNumberEnumAddressRequirement] = Field(
        None,
        description='Whether the phone number requires an [Address](https://www.twilio.com/docs/usage/api/address) registered with Twilio and, if so, what type. Can be: `none`, `any`, `local`, or `foreign`.',
    )
    api_version: Optional[str] = Field(
        None, description='The API version used to start a new TwiML session.'
    )
    beta: Optional[bool] = Field(
        None,
        description='Whether the phone number is new to the Twilio platform. Can be: `true` or `false`.',
    )
    capabilities: Optional[Dict[str, Any]] = Field(
        None,
        description='The set of Boolean properties that indicate whether a phone number can receive calls or messages.  Capabilities are  `Voice`, `SMS`, and `MMS` and each capability can be: `true` or `false`.',
    )
    date_created: Optional[datetime] = Field(
        None,
        description='The date and time in GMT when the resource was created specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.',
    )
    date_updated: Optional[datetime] = Field(
        None,
        description='The date and time in GMT when the resource was last updated specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.',
    )
    friendly_name: Optional[str] = Field(
        None, description='The string that you assigned to describe the resource.'
    )
    links: Optional[Dict[str, Any]] = Field(
        None, description='The URLs of related resources.'
    )
    phone_number: Optional[str] = Field(
        None,
        description='The phone number in [E.164](https://www.twilio.com/docs/glossary/what-e164) format, which consists of a + followed by the country code and subscriber number.',
    )
    sid: Optional[
        constr(pattern=r'^PN[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The unique string that we created to identify the PhoneNumber resource.',
    )
    sms_application_sid: Optional[
        constr(pattern=r'^AP[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the application that handles SMS messages sent to the phone number. If an `sms_application_sid` is present, we ignore all `sms_*_url` values and use those of the application.',
    )
    sms_fallback_method: Optional[SmsFallbackMethod] = Field(
        None,
        description='The HTTP method we use to call `sms_fallback_url`. Can be: `GET` or `POST`.',
    )
    sms_fallback_url: Optional[AnyUrl] = Field(
        None,
        description='The URL that we call using the `sms_fallback_method` when an error occurs while retrieving or executing the TwiML from `sms_url`.',
    )
    sms_method: Optional[SmsMethod] = Field(
        None,
        description='The HTTP method we use to call `sms_url`. Can be: `GET` or `POST`.',
    )
    sms_url: Optional[AnyUrl] = Field(
        None,
        description='The URL we call using the `sms_method` when the phone number receives an incoming SMS message.',
    )
    status_callback: Optional[AnyUrl] = Field(
        None,
        description='The URL we call using the `status_callback_method` to send status information to your application.',
    )
    status_callback_method: Optional[StatusCallbackMethod] = Field(
        None,
        description='The HTTP method we use to call `status_callback`. Can be: `GET` or `POST`.',
    )
    trunk_sid: Optional[
        constr(pattern=r'^TK[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the Trunk that handles calls to the phone number. If a `trunk_sid` is present, we ignore all of the voice URLs and voice applications and use those set on the Trunk. Setting a `trunk_sid` will automatically delete your `voice_application_sid` and vice versa.',
    )
    url: Optional[AnyUrl] = Field(None, description='The absolute URL of the resource.')
    voice_application_sid: Optional[
        constr(pattern=r'^AP[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the application that handles calls to the phone number. If a `voice_application_sid` is present, we ignore all of the voice URLs and use those set on the application. Setting a `voice_application_sid` will automatically delete your `trunk_sid` and vice versa.',
    )
    voice_caller_id_lookup: Optional[bool] = Field(
        None,
        description="Whether we look up the caller's caller-ID name from the CNAM database ($0.01 per look up). Can be: `true` or `false`.",
    )
    voice_fallback_method: Optional[VoiceFallbackMethod] = Field(
        None,
        description='The HTTP method that we use to call `voice_fallback_url`. Can be: `GET` or `POST`.',
    )
    voice_fallback_url: Optional[AnyUrl] = Field(
        None,
        description='The URL that we call using the `voice_fallback_method` when an error occurs retrieving or executing the TwiML requested by `url`.',
    )
    voice_method: Optional[VoiceMethod] = Field(
        None,
        description='The HTTP method we use to call `voice_url`. Can be: `GET` or `POST`.',
    )
    voice_url: Optional[AnyUrl] = Field(
        None,
        description='The URL we call using the `voice_method` when the phone number receives a call. The `voice_url` is not be used if a `voice_application_sid` or a `trunk_sid` is set.',
    )


class TrunkingV1TrunkRecording(BaseModel):
    mode: Optional[RecordingEnumRecordingMode] = Field(
        None,
        description='The recording mode for the trunk. Can be do-not-record (default), record-from-ringing, record-from-answer, record-from-ringing-dual, or record-from-answer-dual.',
    )
    trim: Optional[RecordingEnumRecordingTrim] = Field(
        None,
        description='The recording trim setting for the trunk. Can be do-not-trim (default) or trim-silence.',
    )


class Meta(BaseModel):
    first_page_url: Optional[AnyUrl] = None
    key: Optional[str] = None
    next_page_url: Optional[AnyUrl] = None
    page: Optional[int] = None
    page_size: Optional[int] = None
    previous_page_url: Optional[AnyUrl] = None
    url: Optional[AnyUrl] = None


class V1TrunksGetResponse(BaseModel):
    meta: Optional[Meta] = None
    trunks: Optional[List[TrunkingV1Trunk]] = None


class V1TrunksPostRequest(BaseModel):
    CnamLookupEnabled: Optional[bool] = Field(
        None,
        description='Whether Caller ID Name (CNAM) lookup should be enabled for the trunk. If enabled, all inbound calls to the SIP Trunk from the United States and Canada automatically perform a CNAM Lookup and display Caller ID data on your phone. See [CNAM Lookups](https://www.twilio.com/docs/sip-trunking#CNAM) for more information.',
    )
    DisasterRecoveryMethod_1: Optional[DisasterRecoveryMethod] = Field(
        None,
        alias='DisasterRecoveryMethod',
        description='The HTTP method we should use to call the `disaster_recovery_url`. Can be: `GET` or `POST`.',
    )
    DisasterRecoveryUrl: Optional[AnyUrl] = Field(
        None,
        description='The URL we should call using the `disaster_recovery_method` if an error occurs while sending SIP traffic towards the configured Origination URL. We retrieve TwiML from the URL and execute the instructions like any other normal TwiML call. See [Disaster Recovery](https://www.twilio.com/docs/sip-trunking#disaster-recovery) for more information.',
    )
    DomainName: Optional[str] = Field(
        None,
        description='The unique address you reserve on Twilio to which you route your SIP traffic. Domain names can contain letters, digits, and `-` and must end with `pstn.twilio.com`. See [Termination Settings](https://www.twilio.com/docs/sip-trunking#termination) for more information.',
    )
    FriendlyName: Optional[str] = Field(
        None,
        description='A descriptive string that you create to describe the resource. It can be up to 64 characters long.',
    )
    Secure: Optional[bool] = Field(
        None,
        description='Whether Secure Trunking is enabled for the trunk. If enabled, all calls going through the trunk will be secure using SRTP for media and TLS for signaling. If disabled, then RTP will be used for media. See [Secure Trunking](https://www.twilio.com/docs/sip-trunking#securetrunking) for more information.',
    )
    TransferCallerId: Optional[TrunkEnumTransferCallerId] = Field(
        None,
        description='Caller Id for transfer target. Can be: `from-transferee` (default) or `from-transferor`.',
    )
    TransferMode: Optional[TrunkEnumTransferSetting] = Field(
        None,
        description='The call transfer settings for the trunk. Can be: `enable-all`, `sip-only` and `disable-all`. See [Transfer](https://www.twilio.com/docs/sip-trunking/call-transfer) for more information.',
    )


class V1TrunksSidPostRequest(BaseModel):
    CnamLookupEnabled: Optional[bool] = Field(
        None,
        description='Whether Caller ID Name (CNAM) lookup should be enabled for the trunk. If enabled, all inbound calls to the SIP Trunk from the United States and Canada automatically perform a CNAM Lookup and display Caller ID data on your phone. See [CNAM Lookups](https://www.twilio.com/docs/sip-trunking#CNAM) for more information.',
    )
    DisasterRecoveryMethod_1: Optional[DisasterRecoveryMethod] = Field(
        None,
        alias='DisasterRecoveryMethod',
        description='The HTTP method we should use to call the `disaster_recovery_url`. Can be: `GET` or `POST`.',
    )
    DisasterRecoveryUrl: Optional[AnyUrl] = Field(
        None,
        description='The URL we should call using the `disaster_recovery_method` if an error occurs while sending SIP traffic towards the configured Origination URL. We retrieve TwiML from the URL and execute the instructions like any other normal TwiML call. See [Disaster Recovery](https://www.twilio.com/docs/sip-trunking#disaster-recovery) for more information.',
    )
    DomainName: Optional[str] = Field(
        None,
        description='The unique address you reserve on Twilio to which you route your SIP traffic. Domain names can contain letters, digits, and `-` and must end with `pstn.twilio.com`. See [Termination Settings](https://www.twilio.com/docs/sip-trunking#termination) for more information.',
    )
    FriendlyName: Optional[str] = Field(
        None,
        description='A descriptive string that you create to describe the resource. It can be up to 64 characters long.',
    )
    Secure: Optional[bool] = Field(
        None,
        description='Whether Secure Trunking is enabled for the trunk. If enabled, all calls going through the trunk will be secure using SRTP for media and TLS for signaling. If disabled, then RTP will be used for media. See [Secure Trunking](https://www.twilio.com/docs/sip-trunking#securetrunking) for more information.',
    )
    TransferCallerId: Optional[TrunkEnumTransferCallerId] = Field(
        None,
        description='Caller Id for transfer target. Can be: `from-transferee` (default) or `from-transferor`.',
    )
    TransferMode: Optional[TrunkEnumTransferSetting] = Field(
        None,
        description='The call transfer settings for the trunk. Can be: `enable-all`, `sip-only` and `disable-all`. See [Transfer](https://www.twilio.com/docs/sip-trunking/call-transfer) for more information.',
    )


class V1TrunksTrunkSidCredentialListsGetResponse(BaseModel):
    credential_lists: Optional[List[TrunkingV1TrunkCredentialList]] = None
    meta: Optional[Meta] = None


class V1TrunksTrunkSidCredentialListsPostRequest(BaseModel):
    CredentialListSid: constr(
        pattern=r'^CL[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Field(
        ...,
        description='The SID of the [Credential List](https://www.twilio.com/docs/voice/sip/api/sip-credentiallist-resource) that you want to associate with the trunk. Once associated, we will authenticate access to the trunk against this list.',
    )


class V1TrunksTrunkSidIpAccessControlListsGetResponse(BaseModel):
    ip_access_control_lists: Optional[List[TrunkingV1TrunkIpAccessControlList]] = None
    meta: Optional[Meta] = None


class V1TrunksTrunkSidIpAccessControlListsPostRequest(BaseModel):
    IpAccessControlListSid: constr(
        pattern=r'^AL[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Field(
        ...,
        description='The SID of the [IP Access Control List](https://www.twilio.com/docs/voice/sip/api/sip-ipaccesscontrollist-resource) that you want to associate with the trunk.',
    )


class V1TrunksTrunkSidOriginationUrlsGetResponse(BaseModel):
    meta: Optional[Meta] = None
    origination_urls: Optional[List[TrunkingV1TrunkOriginationUrl]] = None


class V1TrunksTrunkSidOriginationUrlsPostRequest(BaseModel):
    Enabled: bool = Field(
        ..., description='Whether the URL is enabled. The default is `true`.'
    )
    FriendlyName: str = Field(
        ...,
        description='A descriptive string that you create to describe the resource. It can be up to 64 characters long.',
    )
    Priority: int = Field(
        ...,
        description='The relative importance of the URI. Can be an integer from 0 to 65535, inclusive, and the default is 10. The lowest number represents the most important URI.',
    )
    SipUrl: AnyUrl = Field(
        ...,
        description='The SIP address you want Twilio to route your Origination calls to. This must be a `sip:` schema.',
    )
    Weight: int = Field(
        ...,
        description='The value that determines the relative share of the load the URI should receive compared to other URIs with the same priority. Can be an integer from 1 to 65535, inclusive, and the default is 10. URLs with higher values receive more load than those with lower ones with the same priority.',
    )


class V1TrunksTrunkSidOriginationUrlsSidPostRequest(BaseModel):
    Enabled: Optional[bool] = Field(
        None, description='Whether the URL is enabled. The default is `true`.'
    )
    FriendlyName: Optional[str] = Field(
        None,
        description='A descriptive string that you create to describe the resource. It can be up to 64 characters long.',
    )
    Priority: Optional[int] = Field(
        None,
        description='The relative importance of the URI. Can be an integer from 0 to 65535, inclusive, and the default is 10. The lowest number represents the most important URI.',
    )
    SipUrl: Optional[AnyUrl] = Field(
        None,
        description='The SIP address you want Twilio to route your Origination calls to. This must be a `sip:` schema. `sips` is NOT supported.',
    )
    Weight: Optional[int] = Field(
        None,
        description='The value that determines the relative share of the load the URI should receive compared to other URIs with the same priority. Can be an integer from 1 to 65535, inclusive, and the default is 10. URLs with higher values receive more load than those with lower ones with the same priority.',
    )


class V1TrunksTrunkSidPhoneNumbersGetResponse(BaseModel):
    meta: Optional[Meta] = None
    phone_numbers: Optional[List[TrunkingV1TrunkPhoneNumber]] = None


class V1TrunksTrunkSidPhoneNumbersPostRequest(BaseModel):
    PhoneNumberSid: constr(
        pattern=r'^PN[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Field(
        ...,
        description='The SID of the [Incoming Phone Number](https://www.twilio.com/docs/phone-numbers/api/incomingphonenumber-resource) that you want to associate with the trunk.',
    )


class V1TrunksTrunkSidRecordingPostRequest(BaseModel):
    Mode: Optional[RecordingEnumRecordingMode] = Field(
        None,
        description='The recording mode for the trunk. Can be do-not-record (default), record-from-ringing, record-from-answer, record-from-ringing-dual, or record-from-answer-dual.',
    )
    Trim: Optional[RecordingEnumRecordingTrim] = Field(
        None,
        description='The recording trim setting for the trunk. Can be do-not-trim (default) or trim-silence.',
    )
